In [1]:
print("hello world")

hello world

In [2]:
#create a lists of values

In [3]:
import pandas as pd

In [4]:
data=[10,20,30,40,50]

In [5]:
#create a series with default index

In [7]:
my_series = pd.Series(data)

In [16]:
print(my_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
#declaring your own index

In [19]:
Index = ["A","B","C","D","E"]

In [ ]:
#UPDATED SERIES,

In [22]:
updated_series = pd.Series(data,Index)

In [26]:
print(updated_series)

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [28]:
updated_series['c']=45

In [29]:
print(updated_series['c'])

45

In [31]:
updated_series['f']=60

In [32]:
print(updated_series['f'])

60

In [33]:
population = {
 'California': 39538223,
 'Texas': 29145505,
 'Florida': 21538187,
 'New York': 20201249,}

In [50]:
df = pd.DataFrame(population,index = Index)

In [51]:
df

   California     Texas   Florida  New York
A    39538223  29145505  21538187  20201249
B    39538223  29145505  21538187  20201249
C    39538223  29145505  21538187  20201249
D    39538223  29145505  21538187  20201249
E    39538223  29145505  21538187  20201249

In [35]:
pop_series=pd.Series(population)

In [38]:
print (pop_series)

California    39538223
Texas         29145505
Florida       21538187
New York      20201249
dtype: int64

In [52]:
data = {
 'State': ['California', 'Texas', 'Florida', 'New York'],
 'Population': [39538223, 29145505, 21538187, 20201249],
 'Area_sq_km': [423970, 695662, 170312, 141297]}

In [54]:
df = pd.DataFrame(data)

In [55]:
df

        State  Population  Area_sq_km
0  California    39538223      423970
1       Texas    29145505      695662
2     Florida    21538187      170312
3    New York    20201249      141297